services:

  mongodb:
    image: mongo:8
    container_name: smart-bin-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: smartbin
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: smart-bin-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mosquitto_sub -h localhost -t '$$SYS/broker/uptime' -C 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: node:20
    container_name: smart-bin-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: npm run dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/smartbin
    depends_on:
      - mongodb
      - mosquitto

volumes:
  mongo_data:
